---
- name: Ensure target directory exists
  file:
    path: /home/ubuntu/udapeople_app
    state: directory

- name: Copy backend package
  unarchive:
    src: /root/project/artifact-backend.tar.gz
    dest: /home/ubuntu/udapeople_app

- name: Build backend
  ignore_errors: yes
  shell: |
    cd /home/ubuntu/udapeople_app
    npm i
    npm run build

- name: Stop and delete already running server
  ignore_errors: yes
  command: pm2 delete all

- name: Start server
  become: true
  shell: |
    cd /home/ubuntu/udapeople_app/dist
    pm2 start -f ./main.js

- name: Print message
  debug:
    msg: "The value of ENVIRONMENT is {{ ENVIRONMENT }}"
  debug:
    msg: "The value of TYPEORM_CONNECTION is {{ TYPEORM_CONNECTION }}"
  debug:
    msg: "The value of TYPEORM_ENTITIES is {{ TYPEORM_ENTITIES }}"
  debug:
    msg: "The value of TYPEORM_HOST is {{ TYPEORM_HOST }}"
  debug:
    msg: "The value of TYPEORM_PORT is {{ TYPEORM_PORT }}"
  debug:
    msg: "The value of TYPEORM_USERNAME is {{ TYPEORM_USERNAME }}"
  debug:
    msg: "The value of TYPEORM_PASSWORD is {{ TYPEORM_PASSWORD }}"
  debug:
    msg: "The value of TYPEORM_DATABASE is {{ TYPEORM_DATABASE }}"