---
- name: Ensure target directory exists
  file:
    path: /home/ubuntu/udapeople_app
    state: directory

- name: Copy backend package
  unarchive:
    src: /root/project/artifact-backend.tar.gz
    dest: /home/ubuntu/udapeople_app

- name: Build backend
  ignore_errors: yes
  shell: |
    cd /home/ubuntu/udapeople_app
    npm i
    npm run build

- name: Stop and delete already running server
  ignore_errors: yes
  command: pm2 delete all

- name: Start server
  become: true
  shell: |
    cd /home/ubuntu/udapeople_app/dist
    pm2 start -f ./main.js
    echo "server app:"
    pm2 ls